### ISSUE TITLE
Overlay the image with a video with transparency

### ISSUE THREAD

**Issue by asyncfinkd** [shotstack/shotstack-sdk-node#22]
Hi Guys,

I have a problem with this topic.

We're gonna do:
- Draw a random image
- Overlay the image with a video with transparency

**Comment by jeffski** [comment]
This should be possible. You can create an image using and [ImageAsset](https://github.com/shotstack/shotstack-sdk-node#imageasset), and a video using a [VideoAsset](https://github.com/shotstack/shotstack-sdk-node#videoasset). Use [clips](https://github.com/shotstack/shotstack-sdk-node#clip) to control playback properties and [tracks](https://github.com/shotstack/shotstack-sdk-node#track) to layer the clips on top of each other.

The video will need to be a QuickTime mov file with alpha channel or it is also possible to use a [luma matte](https://github.com/shotstack/shotstack-sdk-node#lumaasset) to create a mask.

If you need further assistance please post on our [community support forum](https://community.shotstack.io/) ideally with a code sample of what you have tried and someone will be able to help you there.
