### ISSUE TITLE
Video length

### ISSUE THREAD

**Issue by ahmadakhmiev** [shotstack/shotstack-sdk-node#5]
Hi Jeff,

I appreciate the awesome work you've done here. I'm trying out shotstack for a project to see if it can meet the requirements.

It seems that I can do what I need for my project. I have one concern though. Is it possible to programmatically determine the length of the video asset using the api? 

My use case:
I have a bunch of videos (5-6) that I have to stitch together. I don't know the length of the video clips. So for instance when the first video clip ends I want to put int a in between clip before the next clip. How would I know when to put in the in between clip?

Perhaps I need to use a additional library just to figure out the lengths of the video clips?

Cheers

**Comment by jeffski** [comment]
Hi Ahmad,
The API/SDK does not provide this feature directly, you need to explicitly set the length you want the video to play for, so as you describe, you need to know the length.

We are working on a framework to help you build templates and provide utilities that might be useful when working with videos and images.

We have built a utility that lets you inspect/probe a video and get it's length. Have a look at the project/docs here: https://github.com/shotstack/templates#utilities

The project can not yet be installed via npm but you might find a way to work it in to your project or you might be able to extract the code you need.

It uses [exiftool-vendored](https://www.npmjs.com/package/exiftool-vendored) behind the scenes so you might prefer to write your own solution, but our code might give you a head start.

**Comment by ahmadakhmiev** [comment]
Great 👍 👍  I can work with that, so I'll close the issue.

Thank you for the quick response.
